### ISSUE TITLE
luck of api for changing the password.

### ISSUE THREAD

**Issue by aghnu** [cmput404-project-yonder/yonder#104]

**Comment by amohamed11** [comment]
URL: api/author/{AUTHOR_ID}/
    POST: update profile

**Comment by amohamed11** [comment]
Since a User is a one-to-one relation to Author, updating the author endpoint does need to account for updating the User as well. Only the User model includes the password field.

**Comment by amohamed11** [comment]
Double check with Zoe on requirement for changing password. For now, updating `displayName` `github` should ok.

**Comment by amohamed11** [comment]
Ignore `password` update
