### ISSUE TITLE
Stream page displays error on logining in.

### ISSUE THREAD

**Issue by JamieJiHeonKim** [cmput404-project-yonder/yonder#132]
- Stream page bug when logged in (maybe look at the reducer files)
- ~~Help button onHover~~

**Comment by amohamed11** [comment]
Frontend does not wait for backend response on login before requesting author posts & inbox.
Updating line 23 in Stream.jsx to`if (this.props.loading && !this.props.author)` might mitigate this.

**Comment by aghnu** [comment]
loginActions.js

setCurrentAuthor() redirect user to stream page. this could happened before SET_CURRENT_AUTHOR action is processed in loginreducer.
